-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- Schema from Supabase

CREATE TABLE public.resilience_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  GEOID text NOT NULL UNIQUE,
  foot_traffic_score double precision CHECK (foot_traffic_score >= 0::double precision AND foot_traffic_score <= 10::double precision),
  crime_score double precision CHECK (crime_score >= 0::double precision AND crime_score <= 10::double precision),
  flood_risk_score double precision CHECK (flood_risk_score >= 0::double precision AND flood_risk_score <= 10::double precision),
  rent_score double precision CHECK (rent_score >= 0::double precision AND rent_score <= 10::double precision),
  poi_score double precision CHECK (poi_score >= 0::double precision AND poi_score <= 10::double precision),
  avg_rent double precision,
  updated_at timestamp with time zone DEFAULT now(),
  resilience_score double precision DEFAULT (((((COALESCE(foot_traffic_score, (0)::double precision) * (0.35)::double precision) + (COALESCE(crime_score, (0)::double precision) * (0.15)::double precision)) + (COALESCE(flood_risk_score, (0)::double precision) * (0.10)::double precision)) + (COALESCE(rent_score, (0)::double precision) * (0.10)::double precision)) + (COALESCE(poi_score, (0)::double precision) * (0.05)::double precision)),
  CONSTRAINT resilience_zones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tract_crime_trends (
  id integer NOT NULL DEFAULT nextval('tract_crime_trends_id_seq'::regclass),
  GEOID text,
  year_2000 double precision,
  year_2001 double precision,
  year_2002 double precision,
  year_2003 double precision,
  year_2004 double precision,
  year_2005 double precision,
  year_2006 double precision,
  year_2007 double precision,
  year_2008 double precision,
  year_2009 double precision,
  year_2010 double precision,
  year_2011 double precision,
  year_2012 double precision,
  year_2013 double precision,
  year_2014 double precision,
  year_2015 double precision,
  year_2016 double precision,
  year_2017 double precision,
  year_2018 double precision,
  year_2019 double precision,
  year_2020 double precision,
  year_2021 double precision,
  year_2022 double precision,
  year_2023 double precision,
  year_2024 double precision,
  pred_2025 double precision,
  pred_2026 double precision,
  pred_2027 double precision,
  CONSTRAINT tract_crime_trends_pkey PRIMARY KEY (id),
  CONSTRAINT tract_crime_trends_GEOID_fkey FOREIGN KEY (GEOID) REFERENCES public.resilience_zones(GEOID)
);
CREATE TABLE public.tract_demographics (
  id integer NOT NULL DEFAULT nextval('tract_demographics_id_seq'::regclass),
  GEOID text,
  NTA2020_1 text,
  CT2020 text,
  tract_id text,
  Total population integer,
  Male (%) double precision,
  Female (%) double precision,
  Under 5 years (%) double precision,
  5 to 9 years (%) double precision,
  10 to 14 years (%) double precision,
  15 to 19 years (%) double precision,
  20 to 24 years (%) double precision,
  25 to 29 years (%) double precision,
  30 to 34 years (%) double precision,
  35 to 39 years (%) double precision,
  40 to 44 years (%) double precision,
  45 to 49 years (%) double precision,
  50 to 54 years (%) double precision,
  55 to 59 years (%) double precision,
  60 to 64 years (%) double precision,
  65 to 69 years (%) double precision,
  70 to 74 years (%) double precision,
  75 to 79 years (%) double precision,
  80 to 84 years (%) double precision,
  85 years and over (%) double precision,
  Under 18 years (%) double precision,
  65 years and over (%) double precision,
  Median age (years) double precision,
  CONSTRAINT tract_demographics_pkey PRIMARY KEY (id),
  CONSTRAINT tract_demographics_GEOID_fkey FOREIGN KEY (GEOID) REFERENCES public.resilience_zones(GEOID)
);
CREATE TABLE public.tract_economics (
  id integer NOT NULL DEFAULT nextval('tract_economics_id_seq'::regclass),
  tract_id text,
  NTA2020 text,
  CT2020 text,
  GEOID text,
  HHIU10E integer,
  HHI10t14E integer,
  HHI15t24E integer,
  HHI25t34E integer,
  HHI35t49E integer,
  HHI50t74E integer,
  HHI75t99E integer,
  HI100t149E integer,
  HI150t199E integer,
  HHI200plE integer,
  MdHHIncE integer,
  MnHHIncE integer,
  CONSTRAINT tract_economics_pkey PRIMARY KEY (id),
  CONSTRAINT tract_economics_GEOID_fkey FOREIGN KEY (GEOID) REFERENCES public.resilience_zones(GEOID)
);
CREATE TABLE public.tract_foot_traffic_trends (
  id integer NOT NULL DEFAULT nextval('tract_foot_traffic_trends_id_seq'::regclass),
  GEOID text,
  morning_2020 double precision,
  morning_2021 double precision,
  morning_2022 double precision,
  morning_2023 double precision,
  morning_pred_2025 double precision,
  morning_pred_2026 double precision,
  morning_pred_2027 double precision,
  afternoon_2020 double precision,
  afternoon_2021 double precision,
  afternoon_2022 double precision,
  afternoon_2023 double precision,
  afternoon_pred_2025 double precision,
  afternoon_pred_2026 double precision,
  afternoon_pred_2027 double precision,
  evening_2020 double precision,
  evening_2021 double precision,
  evening_2022 double precision,
  evening_2023 double precision,
  evening_pred_2025 double precision,
  evening_pred_2026 double precision,
  evening_pred_2027 double precision,
  average_2020 double precision,
  average_2021 double precision,
  average_2022 double precision,
  average_2023 double precision,
  average_pred_2025 double precision,
  average_pred_2026 double precision,
  average_pred_2027 double precision,
  morning_2024 double precision,
  afternoon_2024 double precision,
  evening_2024 double precision,
  average_2024 double precision,
  morning_afternoon_2020 double precision,
  morning_afternoon_2021 double precision,
  morning_afternoon_2022 double precision,
  morning_afternoon_2023 double precision,
  morning_afternoon_2024 double precision,
  morning_afternoon_pred_2025 double precision,
  morning_afternoon_pred_2026 double precision,
  morning_afternoon_pred_2027 double precision,
  morning_evening_2020 double precision,
  morning_evening_2021 double precision,
  morning_evening_2022 double precision,
  morning_evening_2023 double precision,
  morning_evening_2024 double precision,
  morning_evening_pred_2025 double precision,
  morning_evening_pred_2026 double precision,
  morning_evening_pred_2027 double precision,
  afternoon_evening_2020 double precision,
  afternoon_evening_2021 double precision,
  afternoon_evening_2022 double precision,
  afternoon_evening_2023 double precision,
  afternoon_evening_2024 double precision,
  afternoon_evening_pred_2025 double precision,
  afternoon_evening_pred_2026 double precision,
  afternoon_evening_pred_2027 double precision,
  CONSTRAINT tract_foot_traffic_trends_pkey PRIMARY KEY (id),
  CONSTRAINT tract_foot_traffic_trends_GEOID_fkey FOREIGN KEY (GEOID) REFERENCES public.resilience_zones(GEOID)
);
CREATE TABLE public.tract_race_ethnicity (
  id integer NOT NULL DEFAULT nextval('tract_race_ethnicity_id_seq'::regclass),
  GEOID text,
  total_population integer,
  HMex double precision,
  HCA double precision,
  HCACstRcn double precision,
  HCAGutmln double precision,
  HCAHndrn double precision,
  HCANcrgn double precision,
  HCAPnmn double precision,
  HCASlvdrn double precision,
  HSA double precision,
  HSAArgntn double precision,
  HSABlvn double precision,
  HSAChln double precision,
  HSAClmbn double precision,
  HSAEcudrn double precision,
  HSAPrguyn double precision,
  HSAPrvn double precision,
  HSAUrgyn double precision,
  HSAVnzuln double precision,
  HCH double precision,
  HCHCuban double precision,
  HCHDmncn double precision,
  HCHPrtRcn double precision,
  HOth double precision,
  HOthSpnrd double precision,
  HOthSpnsh double precision,
  HOthSpnAm double precision,
  HOthGrfna double precision,
  WEur double precision,
  WEurAlbn double precision,
  WEurArmn double precision,
  WEurAstrn double precision,
  WEurAzrbjn double precision,
  WEurBlrsn double precision,
  WEurBlgn double precision,
  WEurBsHrz double precision,
  WEurBrtsh double precision,
  WEurBlgrn double precision,
  WEurCrtn double precision,
  WEurCyprt double precision,
  WEurCzch double precision,
  WEurDnsh double precision,
  WEurDtch double precision,
  WEurEnglsh double precision,
  WEurEstn double precision,
  WEurFnnsh double precision,
  WEurFrnch double precision,
  WEurGrgn double precision,
  WEurGrmn double precision,
  WEurGrk double precision,
  WEurHngrn double precision,
  WEurIrsh double precision,
  WEurItln double precision,
  WEurKsvn double precision,
  WEurLtvn double precision,
  WEurLthn double precision,
  WEurMcdn double precision,
  WEurMlts double precision,
  WEurMldvn double precision,
  WEurMntgrn double precision,
  WEurNrwgn double precision,
  WEurPlsh double precision,
  WEurPrtgs double precision,
  WEurRmn double precision,
  WEurRsn double precision,
  WEurScndvn double precision,
  WEurStIrsh double precision,
  WEurSctsh double precision,
  WEurSrbn double precision,
  WEurSlvc double precision,
  WEurSlvk double precision,
  WEurSlvn double precision,
  WEurSwdsh double precision,
  WEurSwiss double precision,
  WEurTrksh double precision,
  WEurUrkrn double precision,
  WEurWlsh double precision,
  WMENA double precision,
  WMENAAlgrn double precision,
  WMENAArab double precision,
  WMENAEgptn double precision,
  WMENAIrn double precision,
  WMENAIrq double precision,
  WMENAIsrl double precision,
  WMENAJrdn double precision,
  WMENALbns double precision,
  WMENAMrcn double precision,
  WMENAPlstn double precision,
  WMENASyrn double precision,
  WMENATnsn double precision,
  WMENAYmn double precision,
  WOth double precision,
  WOthAstrln double precision,
  WOthCndn double precision,
  WOthFrCndn double precision,
  WOthNZlndr double precision,
  BAfrAm double precision,
  BSSAf double precision,
  BSSAfBrknb double precision,
  BSSAfCmrn double precision,
  BSSAfCngls double precision,
  BSSAfEthpn double precision,
  BSSAfGmbn double precision,
  BSSAfGhn double precision,
  BSSAfGnn double precision,
  BSSAfIvrn double precision,
  BSSAfKnyn double precision,
  BSSAfLbrn double precision,
  BSSAfMln double precision,
  BSSAfNgrn double precision,
  BSSAfSngls double precision,
  BSSAfSrLn double precision,
  BSSAfSAfr double precision,
  BSSAfSdns double precision,
  BSSAfTgls double precision,
  BCrb double precision,
  BCrbAntBrb double precision,
  BCrbBhmn double precision,
  BCrbBrbdn double precision,
  BCrbDmncIs double precision,
  BCrbGrndn double precision,
  BCrbHtn double precision,
  BCrbJmcn double precision,
  BCrbKtnNev double precision,
  BCrbStLuc double precision,
  BCrbTrTob double precision,
  BCrbUSVgIs double precision,
  BCrbVncntn double precision,
  BCrbWind double precision,
  BOth double precision,
  AEA double precision,
  AEAChnsNoT double precision,
  AEAJpns double precision,
  AEAKrn double precision,
  AEATwns double precision,
  ACA double precision,
  ACAAfghan double precision,
  ACAKazakh double precision,
  ACAKyrgyz double precision,
  ACATajik double precision,
  ACAUzbek double precision,
  ASA double precision,
  ASAAsnInd double precision,
  ASABngldsh double precision,
  ASANpls double precision,
  ASAPkstn double precision,
  ASASikh double precision,
  ASASrLnkn double precision,
  ASEA double precision,
  ASEABrms double precision,
  ASEACmbdn double precision,
  ASEAFlpn double precision,
  ASEAIndnsn double precision,
  ASEAMlysn double precision,
  ASEASngprn double precision,
  ASEAThai double precision,
  ASEAVtnms double precision,
  AOth double precision,
  AIANAlkNtv double precision,
  AIANAIn double precision,
  AIANAInBfT double precision,
  AIANAInChr double precision,
  AIANCnAmIn double precision,
  AIANMxIn double precision,
  AIANMxInAz double precision,
  AIANSAI double precision,
  AIANSAIEcI double precision,
  AIANSAIGy double precision,
  AIANSAIInc double precision,
  AIANCrb double precision,
  AIANCrbTno double precision,
  AIANMsIn double precision,
  AIANMsInMy double precision,
  NHPIPly double precision,
  NHPIPlyNH double precision,
  NHPIPlySmn double precision,
  NHPIMc double precision,
  NHPIMcChmr double precision,
  SORBlzn double precision,
  SORBrzln double precision,
  SORGuyans double precision,
  CONSTRAINT tract_race_ethnicity_pkey PRIMARY KEY (id),
  CONSTRAINT tract_race_ethnicity_GEOID_fkey FOREIGN KEY (GEOID) REFERENCES public.resilience_zones(GEOID)
);